version: "3"

services:
  python:
    build: ./python
    ports:
      - "5000:5000" # Expose port for Python app

  react:
    build: ./kegdelpol
    ports:
      - "3000:3000" # Expose port for React app
    command: npm start
